apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        # Please replace with your own image form the ACR
        image: dkrizicweudevacrmain.azurecr.io/sample:1.1
        envFrom:
          - configMapRef:
              name: sampleconfig
          - secretRef:
              name: sampledb
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          # needs to return http status code 200 .. <=399
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
          - name: static
            mountPath: /static
            readOnly: true
      volumes:
        - name: static
          configMap:
            name: samplestatic
