apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sampleshared
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: azurefile
